### ISSUE TITLE
Rozpisanie coding style guidelines

### ISSUE THREAD

**Issue by frslus** [Stekh/NPG-Gra-Mastermind#12]

**Comment by Stekh** [comment]
Czy w

SHAPES = [
"circle",
"square",
]

Elementy listy nie powinniy mieć wcięcia?

**Comment by Stekh** [comment]
Warto byłoby też rozważyć używanie docstringów do dokumentacji kodu, ich opis znaleźć możesz [tutaj](https://realpython.com/documenting-python-code/)

**Comment by O5-33** [comment]
> Czy w
> 
> SHAPES = [ "circle", "square", ]
> 
> Elementy listy nie powinniy mieć wcięcia?

Pominny, markdown jest niepełnosprawny

**Comment by O5-33** [comment]
Naprawiono: brak wcięć w elementach listy

**Comment by O5-33** [comment]
Dodano docstringi

**Comment by Stekh** [comment]
Wygląda dobrze, zamykam
