### ISSUE TITLE
Rozpisz zasady gry Mastermind

### ISSUE THREAD

**Issue by Stekh** [Stekh/NPG-Gra-Mastermind#18]
Pomocny może być artykuł https://pl.wikipedia.org/wiki/Mastermind_(gra_planszowa)

**Comment by discowy2-0** [comment]
Proszę @Jsosnowiec o potwierdzenie czy zasady gry są odpowiednio zredagowane i precyzyjnie opisane

**Comment by O5-33** [comment]
LGTM

**Comment by Stekh** [comment]
zamykam
